//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSeekerService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillSet
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<bool> isprimary { get; set; }
        public Nullable<int> candidateid { get; set; }
        public Nullable<double> YearofEx { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
